version: "3.8"

services:
  app:
    build:
      context: ./../
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ./..:/workspace
    tty: true
    command: /bin/bash -c "poetry install"
