version: "3.8"

services:
  app:
    build:
      context: ./../
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ./..:/workspace
    tty: true
    depends_on:
      - db
  db:
    build:
      context: ./
      dockerfile: ./mysql/Dockerfile
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: main_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - db-store:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

volumes:
  db-store:
