name: Continuous Integration of Change to workflow to run pytest-sample

run-name: ${{ github.actor }} is testing out with pytest

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Branch Check
        run: |
          echo Branch: ${{ github.head_ref }}

      - name: Build and Run pytest
        run: |
          docker-compose -f docker/docker-compose.yml up -d --build
          docker-compose -f docker/docker-compose.yml exec app poetry install
          docker-compose -f docker/docker-compose.yml exec app poetry run pytest --cov=. --cov-branch --cov-report=term-missing --junitxml=pytest.xml | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml
