name: Continuous Integration of pytest-sample with docker

run-name: ${{ github.actor }} is testing out with pytest in docker.

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize]

jobs:
  Test:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Branch Check
        run: |
          echo Branch: ${{ github.head_ref }}

      - name: Build Container
        run: |
          docker-compose -f docker/docker-compose.yml up -d --build

      - name: Install Dependencies
        run: |
          docker-compose -f docker/docker-compose.yml exec -T app poetry install

      - name: Run pytest
        run: |
          docker-compose -f docker/docker-compose.yml exec -T app poetry run pytest --cov=. --cov-branch --cov-report=term-missing --junitxml=./pytest-container.xml
      - name: Upload Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: ./*.xml
      - name: Download Artifacts
        if: success() || failure()
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: artifacts/**/*.xml
