name: Continuous Integration of Change to workflow to run pytest-sample

run-name: ${{ github.actor }} is testing out with pytest

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Branch Check
        run: |
          echo Branch: ${{ github.head_ref }}

      - name: Build Container
        run: |
          docker-compose -f docker/docker-compose.yml up -d --build

      - name: Install Dependencies
        run: |
          docker-compose -f docker/docker-compose.yml exec -T app poetry install

      - name: Wait 20s
        run: |
          sleep 10s

      - name: Run pytest
        run: |
          docker-compose -f docker/docker-compose.yml exec -T app poetry run pytest --cov=. --cov-branch --cov-report=term-missing --junitxml=./docker/pytest.xml > ./docker/pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./docker/pytest-coverage.txt
          junitxml-path: ./docker/pytest.xml
