name: Continuous Integration of pytest-sample with docker

run-name: ${{ github.actor }} is testing out with pytest in docker.

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize]

permissions: write-all

jobs:
  Test:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Branch Check
        run: |
          echo Branch: ${{ github.head_ref }}

      - name: Build Container
        run: |
          docker-compose -f docker/docker-compose.yml up -d --build

      - name: Install Dependencies
        run: |
          docker-compose -f docker/docker-compose.yml exec -T app poetry install

      - name: Run pytest
        run: |
          docker-compose -f docker/docker-compose.yml exec -T app poetry run pytest --cov=. --cov-branch --cov-report=term-missing --junitxml=./pytest-container.xml
      - name: Pytest coverage comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml
      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.BADGE_GIST }}
          gistID: b741bc9aa065ec27ebd515d2a63c3c79
          filename: pytest-coverage-comment.json
          label: Coverage
          message: ${{ steps.coverageComment.outputs.coverage }}
          color: ${{ steps.coverageComment.outputs.color }}
          namedLogo: python
